[log]
level = "info"
format = "text"

[performance]
max-procs = 0
max-memory = 0

[prepared-plan-cache]
enabled = true
capacity = 100

[tikv-client]
grpc-connection-count = 4
grpc-keepalive-time = 10
grpc-keepalive-timeout = 3
commit-timeout = "41s"

[binlog]
enable = false
write-timeout = "15s"
ignore-error = false