apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tidb-consumer.fullname" . }}
  labels:
    {{- include "tidb-consumer.labels" . | nindent 4 }}
data:
  app-config.json: |
    {
      "kafka": {
        "brokers": "{{ .Values.config.kafka.brokers }}",
        "topic": "{{ .Values.config.kafka.topic }}",
        "consumerGroup": "{{ .Values.config.kafka.consumerGroup }}",
        "sessionTimeout": {{ .Values.config.kafka.sessionTimeout }},
        "heartbeatInterval": {{ .Values.config.kafka.heartbeatInterval }},
        "maxPollRecords": {{ .Values.config.kafka.maxPollRecords }}
      },
      "elasticsearch": {
        "host": "{{ .Values.config.elasticsearch.host }}",
        "port": {{ .Values.config.elasticsearch.port }},
        "protocol": "{{ .Values.config.elasticsearch.protocol }}",
        "index": "{{ .Values.config.elasticsearch.index }}",
        "username": "{{ .Values.config.elasticsearch.username }}"
      },
      "processing": {
        "batchSize": {{ .Values.config.processing.batchSize }},
        "flushInterval": {{ .Values.config.processing.flushInterval }},
        "maxRetries": {{ .Values.config.processing.maxRetries }},
        "retryDelay": {{ .Values.config.processing.retryDelay }}
      },
      "logging": {
        "level": "{{ .Values.config.logging.level }}",
        "format": "{{ .Values.config.logging.format }}"
      }
    }