{{- if .Values.tidbCluster.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tidb-data-pipeline.fullname" . }}-crd-check
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tidb-data-pipeline.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tidb-data-pipeline.fullname" . }}-crd-check
  labels:
    {{- include "tidb-data-pipeline.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tidb-data-pipeline.fullname" . }}-crd-check
  labels:
    {{- include "tidb-data-pipeline.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tidb-data-pipeline.fullname" . }}-crd-check
subjects:
- kind: ServiceAccount
  name: {{ include "tidb-data-pipeline.fullname" . }}-crd-check
  namespace: {{ .Release.Namespace }}
{{- end }}