{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tidb-data-pipeline.fullname" . }}
  labels:
    {{- include "tidb-data-pipeline.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tidb-data-pipeline.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicies.policyTypes | nindent 4 }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "tidb-data-pipeline.selectorLabels" . | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "tidb-data-pipeline.selectorLabels" . | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
{{- end }}