[server]
addr = "0.0.0.0:8300"
advertise-addr = "ticdc:8300"
log-file = "/logs/ticdc.log"
log-level = "info"
data-dir = "/data/ticdc"
gc-ttl = 86400

[log]
level = "info"
format = "text"

[sorter]
num-concurrent-worker = 4
chunk-size-limit = 999
max-memory-percentage = 30
max-memory-consumption = 17179869184
num-workerpool-goroutine = 16
sort-dir = "/tmp/sorter"