apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      keepCookies: []
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    database: "[tidb-cdc-logs-]YYYY.MM.DD"
    basicAuth: false
    isDefault: false
    jsonData:
      esVersion: "8.10.0"
      includeFrozen: false
      logLevelField: "level"
      logMessageField: "message"
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
      interval: Daily
      timeInterval: "10s"
      maxDocCount: 10000