{{- if .Values.tidb.enabled }}
{{- if .Values.tidb.pd.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tidb-data-pipeline.fullname" . }}-pd
  labels:
    {{- include "tidb-data-pipeline.componentLabels" (dict "component" "pd" "context" .) | nindent 4 }}
spec:
  serviceName: {{ include "tidb-data-pipeline.fullname" . }}-pd-headless
  replicas: {{ .Values.tidb.pd.replicaCount }}
  selector:
    matchLabels:
      {{- include "tidb-data-pipeline.componentSelectorLabels" (dict "component" "pd" "context" .) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "tidb-data-pipeline.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "tidb-data-pipeline.componentSelectorLabels" (dict "component" "pd" "context" .) | nindent 8 }}
    spec:
      {{- include "tidb-data-pipeline.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "tidb-data-pipeline.serviceAccountName" . }}
      securityContext:
        {{- include "tidb-data-pipeline.podSecurityContext" . | nindent 8 }}
      containers:
        - name: pd
          securityContext:
            {{- include "tidb-data-pipeline.containerSecurityContext" . | nindent 12 }}
          image: "{{ .Values.tidb.pd.image.repository }}:{{ .Values.tidb.pd.image.tag }}"
          imagePullPolicy: {{ .Values.tidb.pd.image.pullPolicy }}
          command:
            - /pd-server
            - --name=$(POD_NAME)
            - --data-dir=/data/pd
            - --client-urls=http://0.0.0.0:2379
            - --peer-urls=http://0.0.0.0:2380
            - --advertise-client-urls=http://$(POD_NAME).{{ include "tidb-data-pipeline.fullname" . }}-pd-headless:2379
            - --advertise-peer-urls=http://$(POD_NAME).{{ include "tidb-data-pipeline.fullname" . }}-pd-headless:2380
            - --initial-cluster={{ include "tidb-data-pipeline.fullname" . }}-pd-0=http://{{ include "tidb-data-pipeline.fullname" . }}-pd-0.{{ include "tidb-data-pipeline.fullname" . }}-pd-headless:2380{{ range $i := until (int .Values.tidb.pd.replicaCount) }}{{ if ne $i 0 }},{{ include "tidb-data-pipeline.fullname" $ }}-pd-{{ $i }}=http://{{ include "tidb-data-pipeline.fullname" $ }}-pd-{{ $i }}.{{ include "tidb-data-pipeline.fullname" $ }}-pd-headless:2380{{ end }}{{ end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: client
              containerPort: 2379
              protocol: TCP
            - name: peer
              containerPort: 2380
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: client
            {{- toYaml .Values.healthChecks.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: client
            {{- toYaml .Values.healthChecks.readinessProbe | nindent 12 }}
          {{- include "tidb-data-pipeline.resources" .Values.tidb.pd | nindent 10 }}
          volumeMounts:
            - name: data
              mountPath: /data
      nodeSelector:
        {{- include "tidb-data-pipeline.nodeSelector" . | nindent 8 }}
      affinity:
        {{- include "tidb-data-pipeline.affinity" . | nindent 8 }}
      tolerations:
        {{- include "tidb-data-pipeline.tolerations" . | nindent 8 }}
  {{- if .Values.tidb.pd.persistence.enabled }}
  volumeClaimTemplates:
    {{- include "tidb-data-pipeline.volumeClaimTemplate" (dict "name" "data" "size" .Values.tidb.pd.persistence.size "storageClass" .Values.global.persistence.storageClass) | nindent 4 }}
  {{- else }}
      volumes:
        - name: data
          emptyDir: {}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tidb-data-pipeline.fullname" . }}-pd
  labels:
    {{- include "tidb-data-pipeline.componentLabels" (dict "component" "pd" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.tidb.pd.service.type }}
  ports:
    - port: {{ .Values.tidb.pd.service.clientPort }}
      targetPort: client
      protocol: TCP
      name: client
  selector:
    {{- include "tidb-data-pipeline.componentSelectorLabels" (dict "component" "pd" "context" .) | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tidb-data-pipeline.fullname" . }}-pd-headless
  labels:
    {{- include "tidb-data-pipeline.componentLabels" (dict "component" "pd" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.tidb.pd.service.clientPort }}
      targetPort: client
      protocol: TCP
      name: client
    - port: {{ .Values.tidb.pd.service.peerPort }}
      targetPort: peer
      protocol: TCP
      name: peer
  selector:
    {{- include "tidb-data-pipeline.componentSelectorLabels" (dict "component" "pd" "context" .) | nindent 4 }}
---
{{- include "tidb-data-pipeline.podDisruptionBudget" (dict "component" "pd" "values" .Values.tidb.pd "context" .) }}
{{- end }}
{{- end }}